export { default as User } from "./user.model";
export * from "./categoryPost.model";
export * from "./post.model";
export * from "./typeReport.model";
export * from "./report.model";
export * from "./roomType.model";
export * from "./room.model";
export * from "./bill.model";
export * from "./util.model";
export * from "./categories-utils.model";
